title: GreenRobot Adserver
description: "Open-source, self hosted, API enabled, yield optimization ad server by GreenRobot: Intelligently rotate Adsense, LifeStreetMedia, and other networks & make more money."
google_analytics: 
show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
